# Generated by Django 4.2.3 on 2023-07-14 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('userID', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profilePicture', models.ImageField(upload_to='profileImages')),
                ('dateOfBirth', models.DateField()),
                ('age', models.IntegerField()),
                ('profession', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('location', models.CharField(max_length=200)),
                ('about', models.TextField(max_length=200)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('linkEdin', models.URLField()),
                ('gitHub', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
