# Generated by Django 4.2.3 on 2023-07-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_profile_website_alter_profile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='profileImages'),
        ),
    ]
