# Generated by Django 4.2.3 on 2023-07-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='homeAdress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
