# Generated by Django 4.2.3 on 2023-07-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_profile_homeadress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homeAdress',
            new_name='homeAddress',
        ),
    ]
