# Generated by Django 4.2.3 on 2023-07-20 13:06

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_homeadress_profile_homeaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('postUser', models.CharField(max_length=50)),
                ('postImage', models.ImageField(upload_to='post Images')),
                ('postCaption', models.TextField()),
                ('postCreatedAt', models.DateTimeField(default=datetime.datetime.now)),
                ('postNumberOfLikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userName',
        ),
    ]
