# Generated by Django 4.2.3 on 2023-07-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_remove_profile_email_remove_profile_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.CharField(max_length=500)),
                ('likedByUsername', models.CharField(max_length=200)),
            ],
        ),
    ]
