# Generated by Django 4.2.3 on 2023-07-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollwersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('follower', models.CharField(max_length=160)),
            ],
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='likedByUsername',
            new_name='username',
        ),
    ]
